language: python            
jobs:
  include:
    - name: "Python 3.8.0 on Xenial Linux"
      python: 3.8          
install: 
  - pip3 install --upgrade pip 
  - pip3 install ipython


script: python main.py < test.txt
